image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-preview
    visibility: public
  - port: 9003
    onOpen: ignore
  - port: 3306
    onOpen: ignore

tasks:
  - init: |
      composer create-project symfony/skeleton:"6.4.*" .
      composer require webapp
      composer require --dev symfony/maker-bundle
      composer require --dev codeception/codeception
      composer require --dev codeception/module-symfony
      composer require --dev codeception/module-webdriver
      composer require --dev codeception/module-asserts
      npm install
      npm run build
    command: |
      symfony server:start -d
      gp sync-done server
  
  - name: Selenium
    init: |
      npm install -g selenium-standalone
      selenium-standalone install
    command: |
      gp sync-await server
      selenium-standalone start

vscode:
  extensions:
    - xdebug.php-debug
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - recca0120.vscode-phpunit
    - neilbrayfield.php-docblocker
    - junstyle.php-cs-fixer
    - TheNouillet.symfony-vscode
    - Symfony.vscode-symfony-test-explorer

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true